# ===== CONEXÃO COM O BANCO =====
spring.datasource.url=jdbc:postgresql://localhost:5432/food
spring.datasource.username=postgres
spring.datasource.password=Piter123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#Esse comnado ai de cima conseguimos definir coisas (ddl) e se nao estiver criado noi banco de dados, ele vai criar para gente.

#aqui é apenas uma configuracao para deixar as conexoes coloridas.
spring.output.ansi.enabled=ALWAYS



